name: Build
on:
  workflow_call:

jobs:
  build:
    name: Build
    container: ubuntu:latest
    runs-on:
      - self-hosted
      - k8s-api
      - linux-amd64-m
    timeout-minutes: 240

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        id: build
        run: |
          echo "This is a Build stage"
