name: SDVCF_SIM build and run

on:
  push:
    branches:
      - pipeline

jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          echo dependencies installation ...
          echo dependencies installed.

      - name: Build Project
        run: |
          echo SDVCF_SIM building ...
          echo SDVCF_SIM built.

  # Test Job
  run:
    needs: build

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Run Project
        run: |
          echo ${PWD}
          pip install /home/runner/work/github-sdv-poc-demo-repo/github-sdv-poc-demo-repo/sdvcf_sim-0.0.1-cp311-cp311-linux_x86_64.whl
          sdvcf_sim --system-under-test-manifest system_under_test.yaml
      # - name: Download artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: test artifacts files
      #     path: ./sdvcf_sim/sdv_testing_tool/src/providers/ansible/library/aws/resources/ansible_resources/artifacts
