name: SDVCF_SIM build and run

on:
  push:
    branches:
      - pipeline
env:
  AWS_DEFAULT_REGION: eu-west-1

jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Preinstall
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libtool autoconf libssl-dev libssh-dev cmake

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make
      
      - name: Temporarily save build artifact
        uses: actions/upload-artifact@v3
        with:
          name: binary-unit-tests
          path: ./build/test/gtest_example_unit_tests
          retention-days: 1

  # Test Job
  run:
    needs: build

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      
      - name: Update pip
        run: |
          python -m pip install --upgrade pip
      
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: binary-unit-tests
          path: ./build/test/gtest_example_unit_tests

      - name: Run Project
        run: |
          pip install ./sdvcf_sim-0.0.1-cp311-cp311-linux_x86_64.whl
          
          export AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ env.AWS_SECRET_ACCESS_KEY }}
          export AWS_DEFAULT_REGION=${{ env.AWS_DEFAULT_REGION }}


          export PATH_TO_BINARY=./build/test/gtest_example_unit_tests
          export CLOUD_PROVIDER=AWS
          export SUBNET_ID=subnet-08790dd098fa8b491
          export IMAGE_ID=QNX
          export INSTANCE_TYPE=t2.micro
          
          sdvcf_sim --system-under-test-manifest system_under_test.yaml
